---
apiVersion: monitoring-fits.fits.extensions.config.gardener.cloud/v1alpha1
kind: ControllerConfiguration
alertmanager:
  url: alerts.example.com:443
  username: admin
  password: your-password-here
  pathPrefix: /
  scheme: https
