//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2026 Copyright FI-TS Finanz Informatik Technologie Service.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/fi-ts/gardener-extension-monitoring-fits/pkg/apis/config"
	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AlertmanagerConfig)(nil), (*config.AlertmanagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AlertmanagerConfig_To_config_AlertmanagerConfig(a.(*AlertmanagerConfig), b.(*config.AlertmanagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AlertmanagerConfig)(nil), (*AlertmanagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AlertmanagerConfig_To_v1alpha1_AlertmanagerConfig(a.(*config.AlertmanagerConfig), b.(*AlertmanagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControllerConfiguration)(nil), (*config.ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(a.(*ControllerConfiguration), b.(*config.ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerConfiguration)(nil), (*ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(a.(*config.ControllerConfiguration), b.(*ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ImagePullSecret)(nil), (*config.ImagePullSecret)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ImagePullSecret_To_config_ImagePullSecret(a.(*ImagePullSecret), b.(*config.ImagePullSecret), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ImagePullSecret)(nil), (*ImagePullSecret)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ImagePullSecret_To_v1alpha1_ImagePullSecret(a.(*config.ImagePullSecret), b.(*ImagePullSecret), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PrometheusRuleConfig)(nil), (*config.PrometheusRuleConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PrometheusRuleConfig_To_config_PrometheusRuleConfig(a.(*PrometheusRuleConfig), b.(*config.PrometheusRuleConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.PrometheusRuleConfig)(nil), (*PrometheusRuleConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_PrometheusRuleConfig_To_v1alpha1_PrometheusRuleConfig(a.(*config.PrometheusRuleConfig), b.(*PrometheusRuleConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AlertmanagerConfig_To_config_AlertmanagerConfig(in *AlertmanagerConfig, out *config.AlertmanagerConfig, s conversion.Scope) error {
	out.URL = in.URL
	out.Username = in.Username
	out.Password = in.Password
	out.PathPrefix = in.PathPrefix
	out.Scheme = in.Scheme
	return nil
}

// Convert_v1alpha1_AlertmanagerConfig_To_config_AlertmanagerConfig is an autogenerated conversion function.
func Convert_v1alpha1_AlertmanagerConfig_To_config_AlertmanagerConfig(in *AlertmanagerConfig, out *config.AlertmanagerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_AlertmanagerConfig_To_config_AlertmanagerConfig(in, out, s)
}

func autoConvert_config_AlertmanagerConfig_To_v1alpha1_AlertmanagerConfig(in *config.AlertmanagerConfig, out *AlertmanagerConfig, s conversion.Scope) error {
	out.URL = in.URL
	out.Username = in.Username
	out.Password = in.Password
	out.PathPrefix = in.PathPrefix
	out.Scheme = in.Scheme
	return nil
}

// Convert_config_AlertmanagerConfig_To_v1alpha1_AlertmanagerConfig is an autogenerated conversion function.
func Convert_config_AlertmanagerConfig_To_v1alpha1_AlertmanagerConfig(in *config.AlertmanagerConfig, out *AlertmanagerConfig, s conversion.Scope) error {
	return autoConvert_config_AlertmanagerConfig_To_v1alpha1_AlertmanagerConfig(in, out, s)
}

func autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	out.ImagePullSecret = (*config.ImagePullSecret)(unsafe.Pointer(in.ImagePullSecret))
	out.Alertmanager = (*config.AlertmanagerConfig)(unsafe.Pointer(in.Alertmanager))
	out.PrometheusRule = (*config.PrometheusRuleConfig)(unsafe.Pointer(in.PrometheusRule))
	return nil
}

// Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in, out, s)
}

func autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	out.ImagePullSecret = (*ImagePullSecret)(unsafe.Pointer(in.ImagePullSecret))
	out.Alertmanager = (*AlertmanagerConfig)(unsafe.Pointer(in.Alertmanager))
	out.PrometheusRule = (*PrometheusRuleConfig)(unsafe.Pointer(in.PrometheusRule))
	return nil
}

// Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ImagePullSecret_To_config_ImagePullSecret(in *ImagePullSecret, out *config.ImagePullSecret, s conversion.Scope) error {
	out.DockerConfigJSON = in.DockerConfigJSON
	return nil
}

// Convert_v1alpha1_ImagePullSecret_To_config_ImagePullSecret is an autogenerated conversion function.
func Convert_v1alpha1_ImagePullSecret_To_config_ImagePullSecret(in *ImagePullSecret, out *config.ImagePullSecret, s conversion.Scope) error {
	return autoConvert_v1alpha1_ImagePullSecret_To_config_ImagePullSecret(in, out, s)
}

func autoConvert_config_ImagePullSecret_To_v1alpha1_ImagePullSecret(in *config.ImagePullSecret, out *ImagePullSecret, s conversion.Scope) error {
	out.DockerConfigJSON = in.DockerConfigJSON
	return nil
}

// Convert_config_ImagePullSecret_To_v1alpha1_ImagePullSecret is an autogenerated conversion function.
func Convert_config_ImagePullSecret_To_v1alpha1_ImagePullSecret(in *config.ImagePullSecret, out *ImagePullSecret, s conversion.Scope) error {
	return autoConvert_config_ImagePullSecret_To_v1alpha1_ImagePullSecret(in, out, s)
}

func autoConvert_v1alpha1_PrometheusRuleConfig_To_config_PrometheusRuleConfig(in *PrometheusRuleConfig, out *config.PrometheusRuleConfig, s conversion.Scope) error {
	out.Spec = in.Spec
	return nil
}

// Convert_v1alpha1_PrometheusRuleConfig_To_config_PrometheusRuleConfig is an autogenerated conversion function.
func Convert_v1alpha1_PrometheusRuleConfig_To_config_PrometheusRuleConfig(in *PrometheusRuleConfig, out *config.PrometheusRuleConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_PrometheusRuleConfig_To_config_PrometheusRuleConfig(in, out, s)
}

func autoConvert_config_PrometheusRuleConfig_To_v1alpha1_PrometheusRuleConfig(in *config.PrometheusRuleConfig, out *PrometheusRuleConfig, s conversion.Scope) error {
	out.Spec = in.Spec
	return nil
}

// Convert_config_PrometheusRuleConfig_To_v1alpha1_PrometheusRuleConfig is an autogenerated conversion function.
func Convert_config_PrometheusRuleConfig_To_v1alpha1_PrometheusRuleConfig(in *config.PrometheusRuleConfig, out *PrometheusRuleConfig, s conversion.Scope) error {
	return autoConvert_config_PrometheusRuleConfig_To_v1alpha1_PrometheusRuleConfig(in, out, s)
}
