//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2026 Copyright FI-TS Finanz Informatik Technologie Service.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	monitoring "github.com/fi-ts/gardener-extension-monitoring-fits/pkg/apis/monitoring"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*MonitoringConfig)(nil), (*monitoring.MonitoringConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MonitoringConfig_To_monitoring_MonitoringConfig(a.(*MonitoringConfig), b.(*monitoring.MonitoringConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*monitoring.MonitoringConfig)(nil), (*MonitoringConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_monitoring_MonitoringConfig_To_v1alpha1_MonitoringConfig(a.(*monitoring.MonitoringConfig), b.(*MonitoringConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_MonitoringConfig_To_monitoring_MonitoringConfig(in *MonitoringConfig, out *monitoring.MonitoringConfig, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_MonitoringConfig_To_monitoring_MonitoringConfig is an autogenerated conversion function.
func Convert_v1alpha1_MonitoringConfig_To_monitoring_MonitoringConfig(in *MonitoringConfig, out *monitoring.MonitoringConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_MonitoringConfig_To_monitoring_MonitoringConfig(in, out, s)
}

func autoConvert_monitoring_MonitoringConfig_To_v1alpha1_MonitoringConfig(in *monitoring.MonitoringConfig, out *MonitoringConfig, s conversion.Scope) error {
	return nil
}

// Convert_monitoring_MonitoringConfig_To_v1alpha1_MonitoringConfig is an autogenerated conversion function.
func Convert_monitoring_MonitoringConfig_To_v1alpha1_MonitoringConfig(in *monitoring.MonitoringConfig, out *MonitoringConfig, s conversion.Scope) error {
	return autoConvert_monitoring_MonitoringConfig_To_v1alpha1_MonitoringConfig(in, out, s)
}
